name: Update Rutube Playlist

on:
  push:
    branches: [ main ]
  schedule:
    # Запуск каждые 12 часов (в 00:00 и 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Update playlist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python github_uploader.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Auto-update playlist"
        git push
